chain-code: 2 ## Goerli
required-confirmations: 12
reconnection-interval: 20 ## if the node does not get a block in x seconds, it will reconnect
provider-endpoint: ${DEPOSITS_PROVIDER_ENDPOINT || wss://goerli.infura.io/ws/v3/745ef5cfaf9d405fb03b10a2c21d1f41}
contract-address: ${DEPOSITS_CONTRACT_ADDRESS || 0xb0a194286A901FeAEA39D2b765247BEd64aD4F41}