services:
  kwild:
    image: kwild
    build:
      context: .
      dockerfile: docker/kwild.dockerfile
    environment:
      DEPOSITS_ENABLED: "true"
      DEPOSITS_CHAIN: eth-goerli
      DEPOSITS_PROVIDER_ENDPOINT: wss://goerli.infura.io/ws/v3/745ef5cfaf9d405fb03b10a2c21d1f41
      DEPOSITS_CONTRACT_ADDRESS: 0xb0a194286A901FeAEA39D2b765247BEd64aD4F41
      PG_ENDPOINT: postgres_db_container
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DB: kwil
    ports:
      - "50051:50051"
      - "8080:8080"
    depends_on:
      - postgres_db
    links:
      - postgres_db
    network_mode: bridge
  kwild-gateway:
    image: kwild-gateway
    build:
      context: .
      dockerfile: docker/kwild-gateway.dockerfile
    environment:
      GRPC_CONTAINER_ENDPOINT: kwild:50051
    ports:
      - "8081:8080"
    network_mode: bridge
  postgres_db:
    image: postgres:15.0-alpine
    container_name: postgres_db_container
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./scripts/pg-init-scripts/:/docker-entrypoint-initdb.d/
    network_mode: bridge