required-confirmations: 12
block-timeout: 20 ## seconds
starting-block: 0
block-buffer: 100
chain: eth-mainnet
provider-endpoint: wss://goerli.infura.io/ws/v3/745ef5cfaf9d405fb03b10a2c21d1f41
kv:
  path: ./.kwilbadger