run: $DEPOSITS_ENABLED
required-confirmations: 12
block-timeout: 30 ## seconds
withdrawal-expiration: 100
chain: $DEPOSITS_CHAIN
provider-endpoint: $DEPOSITS_PROVIDER_ENDPOINT
contract-address: $DEPOSITS_CONTRACT_ADDRESS
db:
  host:  $PG_ENDPOINT
  port: $PG_PORT
  user:  $PG_USER
  password:  $PG_PASSWORD
  database:  $PG_DB
keys:
  wallet-key: $DEPOSITS_WALLET_KEY
sync:
  chunk-size: 100000