db-settings: "./db-settings.yaml"
deposit-settings: "./config/deposit-config.yaml"
manager-settings: "./config/manager.yaml"
chain-client: "./config/chain-client.yaml"
deposits: "./config/deposits.yaml"