env-settings: "~/.kwil-server/env-settings.yaml"

wallet-confirmation-publisher: "wallet-confirmation-publisher, ./kafka-topic-settings.yaml"

wallet-confirmation-consumer: "wallet-confirmation-consumer, ./kafka-topic-settings.yaml"

wallet-request-publisher: "wallet-request-publisher, ./kafka-topic-settings.yaml"

wallet-request-consumer: "wallet-request-consumer, ./kafka-topic-settings.yaml"

deposit-settings: "./x/deposits/deposit-config.yaml"
