version: "3"

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Builds the project
    deps: [build:cli, build:api, build:api-gateway]

  build:cli:
    desc: Builds the CLI
    cmds:
      - go build -o ./.build/kwil ./cmd/kwil
    generates:
      - .build/kwil

  build:api:
    desc: Builds the API
    deps: [build:api:pb]
    cmds:
      - go build -o ./.build/kwild ./cmd/kwild
    generates:
      - .build/kwild

  build:api:pb:
    desc: Compiles the protobuf for the API
    cmds:
      - |
        mkdir -p x/proto
        protoc -I proto \
        --go_out=. --go_opt module=kwil \
        --go-grpc_out=. --go-grpc_opt module=kwil \
        --grpc-gateway_out=. --grpc-gateway_opt module=kwil --grpc-gateway_opt generate_unbound_methods=true \
        --openapiv2_out=. --openapiv2_opt allow_merge=true --openapiv2_opt merge_file_name=x/proto/apisvc/api \
        proto/kwil/apisvc/*.proto
    sources:
      - proto/kwil/apisvc/*.proto
    generates:
      - x/proto/apisvc/*

  build:schema:pb:
    desc: Compiles the protobuf for the Schema Service
    cmds:
      - |
        mkdir -p x/proto
        protoc -I proto -I proto/kwil \
        --go_out=. --go_opt module=kwil \
        --go-grpc_out=. --go-grpc_opt module=kwil \
        proto/kwil/schemasvc/*.proto
    sources:
      - proto/kwil/schemasvc/*.proto
    generates:
      - x/proto/schemasvc/*

  build:pb:
    desc: Compiles protobuf files
    cmds:
      - |
        protoc -I proto -I proto/kwil \
        --go_out=. --go_opt module=kwil \
        proto/kwil/{schema,pgschema}/*.proto

  build:api-gateway:
    desc: Builds the API Gateway
    cmds:
      - go build -o ./.build/kwild-gateway ./cmd/kwild-gateway
    generates:
      - .build/kwild-gateway

  cli:
    desc: Runs the CLI
    cmds:
      - go run ./cmd/kwil {{.CLI_ARGS}}

  deps:
    desc: Install tools required to build this app
    cmds:
      - cat tools.go | grep _ | awk -F'"' '{print $2}' | xargs -tI % go install %

  go-install:
    cmds:
      - go install {{.REPO}}

  brew-install:
    cmds:
      - brew install {{.PACKAGE}}
