apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kwil.fullname" . }}
  labels:
    {{- include "kwil.labels" . | nindent 4 }}
data:
  {{- $grpcHost := include "kwild.fullname" .Subcharts.kwild }}
  {{ $graphqlHost := printf "%s-hasura" .Release.Name -}}
  GRAPHQL_ENDPOINT: {{ printf "http://%s:%d" $graphqlHost (int .Values.kwild.hasura.service.ports.hasura) | quote }}
  GRPC_ENDPOINT: {{ printf "%s:%d" $grpcHost (int .Values.kwild.service.ports.kwild) | quote }}
  GATEWAY_CORS: {{ .Values.kwil.cors | quote | default "" }}
  HEALTHCHECK_KEY: {{ .Values.kwil.healthcheckKey | sha256sum }}