apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kwil.fullname" . }}
  labels:
    {{- include "kwil.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kwil.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kwil.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kwil.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "hasura.initContainers.db" .Subcharts.hasura | nindent 8 }}
        {{- include "kwil.initContainers.hasura" . | nindent 8 }}
      containers:
        - name: {{ printf "%s-kwild" .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp-kwild
              containerPort: {{ .Values.containerPorts.kwild }}
              protocol: TCP
            - name: tcp-gateway
              containerPort: {{ .Values.containerPorts.gateway }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "kwil.fullname" . }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # TODO: loop over .Values.configMapMnt
          volumeMounts:
          - name: cfmp-mnt
            mountPath: /app/keys.json
            subPath: keys.json
            readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      # TODO: loop over .Values.configMapMnt
      volumes:
      - name: cfmp-mnt
        configMap:
          name: {{ include "kwil.configMapVolume.name" . }}
        