# NodePort: map containers port to localhost
service:
  type: NodePort
  # comment nodePorts to enable multi instances on local machine
  nodePorts:
    kwild: 32101


postgresql:
  primary:
    service:
      type: NodePort
      # comment nodePorts to enable multi instances on local machine
      nodePorts:
        postgresql: 32103