broker-settings: &broker-settings
  bootstrap.servers: ${KAFKA_CLUSTER.ENDPOINT}
  username: ${KAFKA_CLUSTER.USER}
  password: ${KAFKA_CLUSTER.PASSWORD}

messaging-emitter:
  broker-settings: *broker-settings
  default-topic: kwil_chain_txns
  linger-ms: 75

messaging-receiver:
  broker-settings: *broker-settings
  topic: kwil_chain_txns
  group-id: kwil_chain_txns_to_db_cg_test
  auto-offset-reset: earliest
  enable.auto.commit: false
  