broker-settings: &broker-settings
  bootstrap.servers: ${KAFKA_CLUSTER.ENDPOINT}
  username: ${KAFKA_CLUSTER.USER}
  password: ${KAFKA_CLUSTER.PASSWORD}

wallet-request-publisher:
    broker-settings: *broker-settings
    default-topic: wallet_requests
    linger-ms: 75

wallet-request-consumer:
    broker-settings: *broker-settings
    topic: wallet_requests
    ## currently using transient consumer ##
    # group-id: kwil_wallet_requests_cg_test
    # auto-offset-reset: earliest
    # enable.auto.commit: false

wallet-confirmation-publisher:
    broker-settings: *broker-settings
    default-topic: wallet_confirmations
    linger-ms: 75

wallet-confirmation-consumer:
    broker-settings: *broker-settings
    topic: wallet_confirmations
    # will always be a transient consumer