env-settings: "~/.kwil-server/env-settings-test.yaml"

wallet-confirmation-publisher: "wallet-confirmation-publisher, ../mx/test-kafka-topic-settings.yaml"

wallet-confirmation-consumer: "wallet-confirmation-consumer, ../mx/test-kafka-topic-settings.yaml"

wallet-request-publisher: "wallet-request-publisher, ../mx/test-kafka-topic-settings.yaml"

wallet-request-consumer: "wallet-request-consumer, ../mx/test-kafka-topic-settings.yaml"

