run: ${DEPOSITS_ENABLED || false}
required-confirmations: 12
block-timeout: 30 ## seconds
withdrawal-expiration: 100 #default: 100
chain: ${DEPOSITS_CHAIN || eth-goerli}
provider-endpoint: ${DEPOSITS_PROVIDER_ENDPOINT || wss://goerli.infura.io/ws/v3/745ef5cfaf9d405fb03b10a2c21d1f41}
contract-address: ${DEPOSITS_CONTRACT_ADDRESS || 0xb0a194286A901FeAEA39D2b765247BEd64aD4F41}
keys:
  wallet-key: ${DEPOSITS_WALLET_KEY || 274194b20d248d47c05913c039c65783647e527aa6360e5e143417f8bb50b988}
sync:
  chunk-size: 100000 

