required-confirmations: 12
block-timeout: 30 ## seconds
withdrawal-expiration: 100
chain: eth-goerli
provider-endpoint: wss://goerli.infura.io/ws/v3/745ef5cfaf9d405fb03b10a2c21d1f41
contract-address: 0xE2d83Ee0A79F5654406B24d5BE65d0e30B12ABeA
kv:
  path: ./.kwilbadger
keys:
  key-path: "./keys/ethereum.pem"
sync:
  chunk-size: 100000