run: true
required-confirmations: 12
block-timeout: 30 ## seconds
withdrawal-expiration: 100
chain: eth-goerli
provider-endpoint: wss://goerli.infura.io/ws/v3/745ef5cfaf9d405fb03b10a2c21d1f41
contract-address: 0xF126AFd800C2435230e0f193aBb95050639D9776
db:
  host: localhost
  port: 5432
  user: postgres
  password: password
  database: postgres
  SSL: false
keys:
  key-path: "./keys/ethereum.pem"
sync:
  chunk-size: 100000