run: false
required-confirmations: 12
block-timeout: 30 ## seconds
withdrawal-expiration: 100
chain: eth-goerli
provider-endpoint: wss://goerli.infura.io/ws/v3/745ef5cfaf9d405fb03b10a2c21d1f41
contract-address: 0xb0a194286A901FeAEA39D2b765247BEd64aD4F41
keys:
  key-path: "./keys/ethereum.pem"
sync:
  chunk-size: 100000