version: "3"

tasks:
  build:sql:
    desc: Builds the SQL repository files for the Deposits microservice
    cmds:
      - sqlc generate
    sources:
      - sql/*.sql
    generates:
      - repository