broker-settings: &broker-settings
  bootstrap.servers: ${kenv.KAFKA_CLUSTER_ENDPOINT}
  session.timeout.ms: 45000
  security.protocol: SASL_SSL
  sasl:
    mechanism: PLAIN
    username: ${kenv.KAFKA_CLUSTER_USER}
    password: ${kenv.KAFKA_CLUSTER_PASSWORD}

messaging-producer-service-test:
  broker-settings: *broker-settings
  topic: kwil_chain_txns
  linger-ms: 75

messaging-consumer-service-test:
  broker-settings: *broker-settings
  topic: kwil_chain_txns
  group-id: kwil_chain_txns_to_db_cg_test
  auto-offset-reset: earliest