broker-settings: &broker-settings
  bootstrap.servers: ${kenv.KAFKA_CLUSTER_ENDPOINT}
  username: ${kenv.KAFKA_CLUSTER_USER}
  password: ${kenv.KAFKA_CLUSTER_PASSWORD}

messaging-emitter:
  broker-settings: *broker-settings
  default-topic: kwil_chain_txns
  linger-ms: 75

messaging-receiver:
  broker-settings: *broker-settings
  topic: kwil_chain_txns
  group-id: kwil_chain_txns_to_db_cg_test
  auto-offset-reset: earliest
  enable.auto.commit: false