version: '3'

tasks:
  ## Compile all protobufs
  compile:all:
    desc: Compiles all protobufs
    cmds:
      - |
        protoc -I ./proto \
        --go_out=. --go_opt module=kwil \
        --go-grpc_out=. --go-grpc_opt module=kwil \
        --grpc-gateway_out=. --grpc-gateway_opt module=kwil --grpc-gateway_opt generate_unbound_methods=true \
        --openapiv2_out=. --openapiv2_opt allow_merge=true --openapiv2_opt merge_file_name=api/openapi-spec/api/v0/api \
        proto/kwil/*/v0/*.proto
    sources:
      - proto/kwil/*/v0/*.proto
    generates:
      - protobuf/*/v0/*
      - api/openapi-spec/api/v0/*
