# trigger-test-kgw will run jobs when the CI workflow is successful
name: trigger-test-kgw

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  workflow-context: # for debugging
    name: Dump workflow context
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event.workflow_run) }}
        run: echo "$GITHUB_CONTEXT"


  on-ci-success:
    # run when `CI` workflow is successful, not sure if this will work on forked PRs
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/kgw-test-reuse.yaml
    with:
      # use the branch from the `CI` workflow
      kwil-db-branch:  ${{ github.event.workflow_run.head_branch }}
      kgw-branch: main
    secrets:
      kgw-access-token: ${{ secrets.KGW_MACH_SECRET_FOR_KWILDB }}